add_library(rtp)
target_sources(rtp
    PRIVATE
    rtp_packet.c
    rtp_util.c
    PUBLIC
    rtp.h
    rtp_packet.h
    rtp_util.h
    rtp_err.h
)
target_link_libraries(rtp
    PUBLIC
    compile_opts
    m
    ld_libs
)
target_include_directories(rtp
    PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_DIR}/include>
)

